### ISSUE TITLE
How did you generate

### ISSUE THREAD

**Issue by ghost** [HassamChundrigar/Urdu-Augmented-TextLines-Dataset#1]
@HassamChundrigar 
How did you generate the textlines, and how did you augment them

**Comment by HassamChundrigar** [comment]
I used Photoshop scripting, using Javascript.
For more info, see this
https://www.adobe.com/devnet/photoshop/scripting.html

**Comment by ghost** [comment]
hmmm... Photoshop scripting
have you tried to generate the textlines using anything else

**Comment by HassamChundrigar** [comment]
@deepseek I also used some opencv methods like blur, noise, rotate etc, and Python Library for image augmentation [IMGAUG](https://imgaug.readthedocs.io/en/latest/)
